id: IADC52432
legacy_id: P007022
ocr_import_info:
  bdrc_scan_id: W1PD95802
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T22:27:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T06:21:30.460237+00:00'
last_modified: 2022-09-01 14:23:04.533912
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD95802
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD95802
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ།
  author: སུ་མ་ཏི་རཏྣ།
statistics:
  ocr_word_mean_confidence_index: 0.5750724460546783
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I1PD95821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD95821
      total_pages: 1253
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD95821.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5687480275225592
    legacy_id: v001
  I1PD95822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD95822
      total_pages: 1401
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD95822.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5811477393132044
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
