id: P007022
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD95802
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  volumes:
    38acdb7863664b96ac32ede31bed5908:
      image_group_id: I1PD95821
      title: ''
      volume_number: 1
      total_pages: 1253
    06e4fd846f4c4d69b6aacc4bd88c991f:
      image_group_id: I1PD95822
      title: ''
      volume_number: 2
      total_pages: 1401
ebook_metadata:
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  sku: P007022
  cover: cover.jpg
  layers:
  - pagination
