id: opecha:P007022
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD95802
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ
  volume:
    cd93fda1063c4bc4980b1affefb5f68b:
      image_group_id: I1PD95821
      title: Volume 1 of bod hor gyi brda yig ming tshig don gsum gsal bar byed pa
        mun sel sgron me
      volume_number: 1
      total_pages: 1253
    d864cb6c898c49c2a32b95008153b45c:
      image_group_id: I1PD95822
      title: Volume 2 of bod hor gyi brda yig ming tshig don gsum gsal bar byed pa
        mun sel sgron me
      volume_number: 2
      total_pages: 1401
  author: ''
ebook_metadata:
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  sku: P007022
  cover: cover.jpg
  layers:
  - pagination
