id: P007022
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:47.829516
source_metadata:
  id: bdr:W1PD95802
  title: བོད་ཧོར་གྱི་བརྡ་ཡིག་མིང་ཚིག་དོན་གསུམ་གསལ་བར་བྱེད་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  volumes:
    cd93fda1063c4bc4980b1affefb5f68b:
      image_group_id: I1PD95821
      title: Volume 1 of bod hor gyi brda yig ming tshig don gsum gsal bar byed pa
        mun sel sgron me
      volume_number: 1
      total_pages: 1253
      base_file: v001.txt
    d864cb6c898c49c2a32b95008153b45c:
      image_group_id: I1PD95822
      title: Volume 2 of bod hor gyi brda yig ming tshig don gsum gsal bar byed pa
        mun sel sgron me
      volume_number: 2
      total_pages: 1401
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
